using Mutagen.Bethesda;
using Mutagen.Bethesda.Fallout4;
using Mutagen.Bethesda.FormKeys.Fallout4;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.WPF.Reflection.Attributes;

namespace HeyThatsNotJunk {
	public class Program {
		static Lazy<ProgramSettings> localSettings = null!;

		public static async Task<int> Main (string[] args) {
			return await SynthesisPipeline.Instance
				.AddPatch<IFallout4Mod, IFallout4ModGetter>(RunPatch)
				.SetAutogeneratedSettings(
					nickname: "Settings",
					path: "HeyThatsNotJunk_Settings.json",
					out localSettings
				)
				.SetTypicalOpen(GameRelease.Fallout4, "SYN_HeyThatsNotJunk.esp")
				.Run(args);
		}

		public static void RunPatch (IPatcherState<IFallout4Mod, IFallout4ModGetter> state) {
			foreach (var item in localSettings.Value.MiscNotJunk) {
				var miscItem = item.Resolve(state.LinkCache);

				Console.WriteLine($"{miscItem.Name}");

				var hasNJJAKywd = miscItem.HasKeyword(Fallout4.Keyword.NotJunkJetAmmo);

				if (!hasNJJAKywd || miscItem.Components != null) {
					var overrideMisc = state.PatchMod.MiscItems.GetOrAddAsOverride(miscItem);
					overrideMisc.Components?.Clear();
					if (!hasNJJAKywd) {
						overrideMisc.Keywords ??= new();
						overrideMisc.Keywords.Add(Fallout4.Keyword.NotJunkJetAmmo);
					}
				}
			}
		}
	}

	public class ProgramSettings {
		[MaintainOrder]
		[SettingName("Not Junk")]
		public List<IFormLinkGetter<IMiscItemGetter>> MiscNotJunk =
			new()
			{
				Fallout4.MiscItem.BaseballGlove_PreWar,
				Fallout4.MiscItem.BoS302DanseHoloTag,
				Fallout4.MiscItem.BoSM01_HolotagBrandis,
				Fallout4.MiscItem.BoSM01_HolotagFaris,
				Fallout4.MiscItem.BoSM01_HolotagVarham,
				Fallout4.MiscItem.BoSM02_HolotagRylan,
				Fallout4.MiscItem.BoS_Holotag,
				Fallout4.MiscItem.COMMacCreadyToySolider,
				Fallout4.MiscItem.Camera_Clean,
				Fallout4.MiscItem.ChargeCard,
				Fallout4.MiscItem.CoffeePot01clean,
				Fallout4.MiscItem.DN021_AnnikasLocket,
				Fallout4.MiscItem.DN070_BowlingBall01,
				Fallout4.MiscItem.DN070_BowlingPin02,
				Fallout4.MiscItem.DN070_Camera,
				Fallout4.MiscItem.DN070_Flag_American_TrifoldBox,
				Fallout4.MiscItem.DN070_Globe01,
				Fallout4.MiscItem.DN070_Hairbrush_02_Silver,
				Fallout4.MiscItem.DN070_Pen01,
				Fallout4.MiscItem.DN070_Pencil,
				Fallout4.MiscItem.DN070_SilverLocket,
				Fallout4.MiscItem.DN070_ToyCar,
				Fallout4.MiscItem.DN070_WatchSilver,
				Fallout4.MiscItem.DN155_ToyParts,
				Fallout4.MiscItem.GiddyupButtercup,
				Fallout4.MiscItem.Jangles01,
				Fallout4.MiscItem.MS07bGildedGrasshopper01,
				Fallout4.MiscItem.PrewarMoney,
				Fallout4.MiscItem.SynthDeathItem,
				Fallout4.MiscItem.TeddyBear,
				Fallout4.MiscItem.TeddyBearClean,
				Fallout4.MiscItem.ToyCar_PreWar,
				Fallout4.MiscItem.ToyTruck_PreWar01
			};
	}
}
